version: '3.7'
services:

  web:
    build: .
    # Not sure why I need to double the dollar sign
    command: /bin/bash -c 'DATABASE_URL=$$DATABASE_URL_DEVELOPMENT?sslmode=disable rerun'
    tty: true # Gin's logger won't print color otherwise
    ports:
      - "127.1.3.1:8080:8080" # See: /etc/hosts -> api-golang-gin.reminders.test
    volumes:
      - .:/go/src/app
    depends_on:
      - db
    env_file:
      - ~/.env/ng-reminders/golang-gin/web.env
      - ~/.env/ng-reminders/golang-gin/db.env
    environment:
      - PORT=8080
      - APP_ENV=development
      - DOMAIN=reminders.test
      - ORIGIN=https://ng.reminders.test

  nginx_proxy:
    image: nginx
    ports:
      - "127.1.3.2:443:443"  # See: /etc/hosts -> api-proxy-golang-gin.reminders.test
    depends_on:
      - web
    volumes:
      - ./nginx_dev/:/etc/nginx/conf.d/

  # https://github.com/golang-migrate/migrate/blob/master/database/postgres/TUTORIAL.md
  dbmate:
    image: amacneil/dbmate
    volumes:
      - ./db:/db
    depends_on:
      - db

  psql:
    # https://hub.docker.com/_/postgres
    image: postgres:13
    entrypoint: /bin/bash
    env_file:
      - ~/.env/ng-reminders/golang-gin/db.env
    environment:
      - PGHOST=db
      - PGUSER=postgres
      - PGPASSWORD=$POSTGRES_PASSWORD
    depends_on:
      - db

  db:
    # https://hub.docker.com/_/postgres
    image: postgres:13
    ports:
      - "127.1.3.3:5432:5432" # pg-golang-gin.reminders.test
    restart: always
    env_file:
      - ~/.env/ng-reminders/golang-gin/db.env
    volumes:
      - db-data:/var/lib/postgresql/data
      - /tmp/ng-reminders/golang-gin/dumps/:/tmp/dumps/
      - ./log_all.init.sh:/docker-entrypoint-initdb.d/init.sh

volumes:
  db-data:
