version: '3.7'
services:

  web:
    build: .
    command: rerun
    tty: true # Gin's logger won't print color otherwise
#    init: true # fixes control-c not working
    ports:
      - "127.0.0.6:8080:8080"
    volumes:
      - .:/go/src/app
    depends_on:
      - db
    env_file:
      - ~/.env/ng-reminders/golang-gin/web.env
      - ~/.env/ng-reminders/golang-gin/db.env
    environment:
      - PORT=8080
      - APP_ENV=development
      - ${DATABASE_URL}:$DATABASE_URL_DEVELOPMENT

  nginx_proxy:
    image: nginx
    ports:
      - "127.0.0.7:443:443"
    depends_on:
      - web
    volumes:
      - ./nginx_dev/:/etc/nginx/conf.d/

  # https://github.com/golang-migrate/migrate/blob/master/database/postgres/TUTORIAL.md
  dbmate:
    image: amacneil/dbmate
    volumes:
      - ./db:/db
    depends_on:
      - db

  psql:
    # https://hub.docker.com/_/postgres
    image: postgres:13
    entrypoint: /bin/bash
    env_file:
      - ~/.env/ng-reminders/golang-gin/db.env
    environment:
      - PGHOST=db
      - PGUSER=postgres
      - PGPASSWORD=$POSTGRES_PASSWORD
    depends_on:
      - db

  db:
    # https://hub.docker.com/_/postgres
    image: postgres:13
    ports:
      - "127.0.0.8:5432:5432"
    restart: always
    env_file:
      - ~/.env/ng-reminders/golang-gin/db.env
    volumes:
      - db-data:/var/lib/postgresql/data
      - /tmp/ng-reminders/golang-gin/dumps/:/tmp/dumps/
      - ./log_all.init.sh:/docker-entrypoint-initdb.d/init.sh

volumes:
  db-data:
